# Generated by Django 5.1.1 on 2024-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('cpf', models.IntegerField(blank=True, default=0, null=True)),
                ('rg', models.IntegerField(blank=True, default=0, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('mailbox', models.EmailField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('local_pre', models.CharField(blank=True, max_length=500, null=True)),
                ('event_local', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('input_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('residual_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
