# Generated by Django 5.1.1 on 2024-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cep',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
